Fixed error and mock:
Traceback (most recent call last):
  File "/home/derrick/src/aws-log-parser/examples/count-hosts.py", line 103, in <module>
    main()
  File "/home/derrick/src/aws-log-parser/examples/count-hosts.py", line 100, in main
    count_ips(entries, ip_attr)
  File "/home/derrick/src/aws-log-parser/examples/count-hosts.py", line 13, in count_ips
    counter = Counter(attrgetter(ip_attr)(entry) for entry in entries)
  File "/home/derrick/.pyenv/versions/3.10.9/lib/python3.10/collections/__init__.py", line 577, in __init__
    self.update(iterable, **kwds)
  File "/home/derrick/.pyenv/versions/3.10.9/lib/python3.10/collections/__init__.py", line 670, in update
    _count_elements(self, iterable)
  File "/home/derrick/src/aws-log-parser/examples/count-hosts.py", line 13, in <genexpr>
    counter = Counter(attrgetter(ip_attr)(entry) for entry in entries)
  File "/home/derrick/src/aws-log-parser/aws_log_parser/interface.py", line 180, in read_url
    yield from self.read_s3(
  File "/home/derrick/src/aws-log-parser/aws_log_parser/interface.py", line 145, in read_s3
    yield from self.parse(
  File "/home/derrick/src/aws-log-parser/aws_log_parser/interface.py", line 92, in parse
    yield from log_entries
  File "/home/derrick/src/aws-log-parser/aws_log_parser/interface.py", line 70, in parse_csv
    for row in csv.reader(content, delimiter=self.log_type.delimiter):
  File "/home/derrick/src/aws-log-parser/aws_log_parser/aws/s3.py", line 49, in read_keys
    yield from self.read_key(bucket, file["Key"])
  File "/home/derrick/src/aws-log-parser/aws_log_parser/aws/s3.py", line 36, in read_key
    fileobj=BytesIO(contents["Body"].iter_lines()),
TypeError: a bytes-like object is required, not 'generator'